# Generated by Django 4.1.6 on 2023-02-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('count', models.PositiveIntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('is_published', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='news.tag')),
            ],
        ),
    ]
