# Generated by Django 4.1.7 on 2023-04-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_status_dislike_news_status_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='status_dislike',
        ),
        migrations.RemoveField(
            model_name='news',
            name='status_like',
        ),
    ]
